version: "3"
services:
    mongodb:
        image: mongo
        restart: always
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - webappnetwork
    api:
        container_name: webapp-api
        build: ./
        restart: always
        ports:
            - "4000:4000"
            - "80:4000"
        volumes:
            - .:/home/node/api
        working_dir: /home/node/api
        depends_on:
            - mongodb
            - redis
        networks:
            - webappnetwork
        # command: npm run serve
        env_file: .env
        environment:
            WAIT_HOSTS: mongodb:27017, redis:6379
            MONGODB_HOST: mongodb
            REDIS_HOST: redis
networks:
    webappnetwork:
        driver: bridge